---

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install nfs-utils when ansible_os_family is RedHat
  yum: name="{{ item }}" state=installed
  with_items: nfs_packages
  when: ansible_os_family == "RedHat"

- name: Install nfs-kernel-server when ansible_os_family is Debian
  apt: name="{{ item }}" state=installed
  with_items: nfs_packages
  when: ansible_os_family == "Debian"

- name: Ensure NFS service started and enabled
  service: name="{{ item }}" state=started enabled=yes
  with_items: nfs_services

- name: Setup Ports
  lineinfile: dest="{{ nfs_config_file }}"
              regexp="^#?{{ item.name }}"
              line='{{ item.name }}={{ item.value }}'
  with_items: nfs_ports
  notify: restart nfs services

- name: Ensure exported directory exists
  file: path="{{ item.path }}" state=directory
        owner='{{ item.owner|default(nfs_default_owner) }}'
        group='{{ item.group|default(nfs_default_group) }}'
        mode='{{ item.mode|default("0777") }}'
  with_items: nfs_exported_directories

- name: Ensure exported directories are in /etc/exports
  lineinfile: dest=/etc/exports
              regexp="^{{ item.path }}\s"
              line='{{ item.path }} {% for host in item.hosts %} {{ host.name }}({{ host.options|default([])|join(",") }}){% endfor %}'
  with_items: nfs_exported_directories
  notify: refresh exports